# Generated by Django 5.2.5 on 2025-08-30 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomeGrupo', models.CharField(max_length=100)),
                ('nomeCategoria', models.CharField(max_length=100)),
                ('nomeDescricao', models.CharField(max_length=100)),
                ('tipoTransacao', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('idPagamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('valorPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataPagamentoPrevisto', models.DateField()),
                ('dataPagamentoRealizado', models.DateField()),
                ('statusPagamento', models.CharField(choices=[('antes', 'A pagar'), ('vencendo', 'Vencendo'), ('pago', 'Pago')], max_length=50)),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlefinanceiro.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('idReceber', models.BigAutoField(primary_key=True, serialize=False)),
                ('valorReceber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataRecebimentoPrevista', models.DateField()),
                ('dataRecebimentoEfetiva', models.DateField()),
                ('statusRecebimento', models.CharField(choices=[('aguardando', 'Aguardando'), ('vencendo', 'Na Data'), ('recebido', 'Recebido')], max_length=50)),
                ('observacaoRecebimento', models.TextField()),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlefinanceiro.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('idTransacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('valorTransacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricaoTransacao', models.CharField(max_length=100)),
                ('dataTransacao', models.DateField()),
                ('dataCriacao', models.DateField(auto_now_add=True)),
                ('dataAtualizacao', models.DateField(auto_now=True)),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlefinanceiro.categoria')),
            ],
        ),
    ]
