# Generated by Django 5.2.5 on 2025-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinanceiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='dataPagamentoPrevisto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='dataPagamentoRealizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='dataRecebimentoEfetiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='dataRecebimentoPrevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
